apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kro-controller
  namespace: argocd
spec:
  project: default
  source:
    repoURL: registry.k8s.io/kro/charts
    chart: kro
    targetRevision: 0.7.1
  destination:
    server: https://kubernetes.default.svc
    namespace: kro-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
